spring.application.name=aemud-api
spring.datasource.url=jdbc:mysql://localhost:3306/aemud?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Wollaj@1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true